const labels = {
  'value-prop': 'Clarify your core offer headline so a visitor immediately understands what is sold.',
  'cta-fold': 'Move the primary CTA above the fold and keep it visible on mobile.',
  'lead-capture': 'Add a simple lead form, booking widget, or direct contact action in one click.',
  'trust': 'Add genuine, permissioned proof that is relevant to the offer, such as verified reviews, approved client logos, documented before-and-after examples, or a sourced case study.',
  'mobile': 'Improve spacing, tap targets, and readability for mobile conversion users.',
  'speed': 'Compress hero images, defer non-critical scripts, and remove render-blocking assets.',
  'content': 'Add FAQ, pricing clarity, and scope details that answer objections.',
  'contact': 'Move contact information and response-time expectations into the hero and footer.',
  'analytics': 'Confirm appropriate analytics, conversion measurement, privacy disclosures, and consent controls for the website jurisdiction and business requirements.',
  'retargeting': 'Confirm the follow-up path and privacy disclosures are appropriate before collecting or using visitor data.'
};

const sliderData = {
  'value-prop': 0,
  'cta-fold': 0,
  'lead-capture': 0,
  'trust': 0,
  'mobile': 0,
  'speed': 0,
  'content': 0,
  'contact': 0,
  'analytics': 0,
  'retargeting': 0,
};

function updateScore() {
  const sliders = document.querySelectorAll('#audit-form input[type=range]');
  let total = 0;
  const scored = [];

  sliders.forEach((slider) => {
    const key = slider.dataset.label;
    const value = Number(slider.value);
    sliderData[key] = value;
    total += value;
    scored.push({ key, value });
  });

  const criticalGap = scored.some(item => item.value <= 1);
  const scoreBand = total >= 40
    ? (criticalGap ? 'Strong overall – critical gap present' : 'Strong overall – review any critical gaps before launch')
    : total >= 30
      ? 'Good – fix priority gaps'
      : total >= 20
        ? 'Fair – needs structured optimization'
        : 'Needs work – first-pass recommendations required';

  const output = document.getElementById('score-output');
  document.getElementById('total-score').textContent = `${total}`;
  document.getElementById('score-band').textContent = scoreBand;

  const fixList = document.getElementById('fix-list');
  fixList.innerHTML = '';
  const recommendations = scored
    .filter((item) => item.value <= 3)
    .sort((a, b) => a.value - b.value)
    .slice(0, 5)
    .map((item) => labels[item.key]);

  if (recommendations.length === 0) {
    recommendations.push(total >= 40
      ? 'All core areas scored strongly. Consider testing hero, offer, and CTA variants.'
      : 'No severe single-area failure detected, but the total score still needs stronger proof, clearer CTA flow, and trust signals.');
  }

  recommendations.forEach((text) => {
    const li = document.createElement('li');
    li.textContent = text;
    fixList.appendChild(li);
  });

  document.getElementById('score-text').textContent = 'Here is your scorecard summary.';
  output.classList.remove('hidden');

  const brandEmail = document.getElementById('brand-email').value.trim();
  const brandName = document.getElementById('brand-name').value.trim() || 'Your Brand';
  const ctaText = document.getElementById('cta-text').value.trim() || 'Order my website cleanup';

  const subject = `${brandName} - Website audit score ${total}/50`;
  const body = [
    `Score: ${total}/50`,
    `Band: ${scoreBand}`,
    'Top fixes:',
    ...recommendations.map((text) => `- ${text}`),
    'Generated by Website Audit Scorecard mini-site.'
  ].join('\n');

  const cta = document.getElementById('cta');
  const email = brandEmail.toLowerCase();
  const usableEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && !email.endsWith('@example.com') && !email.includes('yourbrand') && !email.includes('yourdomain');
  if (usableEmail) {
    cta.textContent = ctaText || 'Preview scorecard email';
    cta.href = `mailto:${encodeURIComponent(brandEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  } else {
    cta.textContent = 'Enter a real email to preview scorecard email';
    cta.removeAttribute('href');
  }
}

document.getElementById('score-btn').addEventListener('click', updateScore);
function syncSliderLabel(slider) {
  const label = slider.closest('fieldset').querySelector('legend').textContent;
  const span = slider.closest('label').querySelector('span').textContent;
  let output = slider.parentElement.querySelector('.slider-value');
  if (!output) {
    output = document.createElement('strong');
    output.className = 'slider-value';
    slider.parentElement.appendChild(output);
  }
  output.textContent = `${slider.value}/5`;
  slider.setAttribute('aria-label', `${label}: ${span} score ${slider.value} out of 5`);
}

document.querySelectorAll('#audit-form input[type=range]').forEach((slider) => {
  syncSliderLabel(slider);
  slider.addEventListener('input', () => syncSliderLabel(slider));
});
