const labels = {
  'value-prop': 'Clarify your core offer headline so a visitor immediately understands what is sold.',
  'cta-fold': 'Move the primary CTA above the fold and keep it visible on mobile.',
  'lead-capture': 'Add a simple lead form, booking widget, or direct contact action in one click.',
  'trust': 'Add 2-3 real testimonials and proof (reviews, logos, before/after, case wins).',
  'mobile': 'Improve spacing, tap targets, and readability for mobile conversion users.',
  'speed': 'Compress hero images, defer non-critical scripts, and remove render-blocking assets.',
  'content': 'Add FAQ, pricing clarity, and scope details that answer objections.',
  'contact': 'Move contact information and response-time expectations into the hero and footer.',
  'analytics': 'Install GA4 + conversion events and verify they fire on lead submission.',
  'retargeting': 'Create at least one retargeting audience and a simple follow-up sequence.'
};

const sliderData = {
  'value-prop': 0,
  'cta-fold': 0,
  'lead-capture': 0,
  'trust': 0,
  'mobile': 0,
  'speed': 0,
  'content': 0,
  'contact': 0,
  'analytics': 0,
  'retargeting': 0,
};

function updateScore() {
  const sliders = document.querySelectorAll('#audit-form input[type=range]');
  let total = 0;
  const lowScorers = [];

  sliders.forEach((slider) => {
    const key = slider.dataset.label;
    const value = Number(slider.value);
    sliderData[key] = value;
    total += value;
    if (value <= 2) {
      lowScorers.push(key);
    }
  });

  const scoreBand = total >= 40
    ? 'Strong – launch-ready'
    : total >= 30
      ? 'Good – fix priority gaps'
      : total >= 20
        ? 'Fair – needs structured optimization'
        : 'Needs work – first-pass recommendations required';

  const output = document.getElementById('score-output');
  document.getElementById('total-score').textContent = `${total}`;
  document.getElementById('score-band').textContent = scoreBand;

  const fixList = document.getElementById('fix-list');
  fixList.innerHTML = '';
  lowScorers
    .slice(0, 5)
    .forEach((key) => {
      const li = document.createElement('li');
      li.textContent = labels[key];
      fixList.appendChild(li);
    });

  if (lowScorers.length === 0) {
    const li = document.createElement('li');
    li.textContent = 'Great job — all core areas are strong. Consider A/B testing hero variants for growth.';
    fixList.appendChild(li);
  }

  document.getElementById('score-text').textContent = 'Here is your scorecard summary.';
  output.classList.remove('hidden');

  const brandEmail = document.getElementById('brand-email').value.trim() || 'hello@yourbrand.com';
  const brandName = document.getElementById('brand-name').value.trim() || 'Your Brand';
  const ctaText = document.getElementById('cta-text').value.trim() || 'Order my website cleanup';

  const subject = `${brandName} - Website audit score ${total}/50`;
  const body = [
    `Score: ${total}/50`,
    `Band: ${scoreBand}`,
    'Top fixes:',
    ...lowScorers.slice(0, 5).map((key) => `- ${labels[key]}`),
    'Generated by Website Audit Scorecard mini-site.'
  ].join('\n');

  const cta = document.getElementById('cta');
  cta.textContent = ctaText;
  cta.href = `mailto:${encodeURIComponent(brandEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

document.getElementById('score-btn').addEventListener('click', updateScore);
document.querySelectorAll('#audit-form input[type=range]').forEach((slider) => {
  slider.addEventListener('input', () => {
    const label = slider.closest('fieldset').querySelector('legend').textContent;
    slider.setAttribute('aria-label', `${label} score ${slider.value}`);
  });
});
