const labels = {
  'value-prop': 'Clarify your core offer headline so a visitor immediately understands what is sold.',
  'cta-fold': 'Move the primary CTA above the fold and keep it visible on mobile.',
  'lead-capture': 'Add a simple lead form, booking widget, or direct contact action in one click.',
  'trust': 'Add genuine, permissioned proof that is relevant to the offer, such as verified reviews, approved client logos, documented before-and-after examples, or a sourced case study.',
  'mobile': 'Improve spacing, tap targets, and readability for mobile conversion users.',
  'speed': 'Compress hero images, defer non-critical scripts, and remove render-blocking assets.',
  'content': 'Add FAQ, pricing clarity, and scope details that answer objections.',
  'contact': 'Move contact information and response-time expectations into the hero and footer.',
  'analytics': 'Confirm appropriate analytics, conversion measurement, privacy disclosures, and consent controls for the website jurisdiction and business requirements.',
  'retargeting': 'Confirm the follow-up path and privacy disclosures are appropriate before collecting or using visitor data.'
};

const sliderData = {};
let hasCalculated = false;

function usableEmail(value) {
  const email = value.trim().toLowerCase();
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && !email.endsWith('@example.com') && !email.includes('yourbrand') && !email.includes('yourdomain');
}

function collectScores() {
  const scored = [];
  document.querySelectorAll('#audit-form input[type=range]').forEach((slider) => {
    const key = slider.dataset.label;
    const value = Number(slider.value);
    sliderData[key] = value;
    scored.push({ key, value, label: slider.closest('label').querySelector('span').textContent });
  });
  return scored;
}

function buildScore() {
  const scored = collectScores();
  const total = scored.reduce((sum, item) => sum + item.value, 0);
  const criticalGap = scored.some(item => item.value <= 1);
  const scoreBand = total >= 40
    ? (criticalGap ? 'Strong overall – critical gap present' : 'Strong overall – review any critical gaps before launch')
    : total >= 30
      ? 'Good – fix priority gaps'
      : total >= 20
        ? 'Fair – needs structured optimization'
        : 'Needs work – first-pass recommendations required';
  const recommendations = scored
    .filter((item) => item.value <= 3)
    .sort((a, b) => a.value - b.value)
    .slice(0, 5)
    .map((item) => labels[item.key]);
  if (recommendations.length === 0) {
    recommendations.push(total >= 40
      ? 'All core areas scored strongly. Consider testing hero, offer, and CTA variants.'
      : 'No severe single-area failure detected, but the total score still needs stronger proof, clearer CTA flow, and trust signals.');
  }
  return { scored, total, criticalGap, scoreBand, recommendations };
}

function contextLines() {
  return [
    `Business or website: ${document.getElementById('website-name').value.trim() || document.getElementById('brand-name').value.trim() || 'Not provided'}`,
    `Website URL: ${document.getElementById('website-url').value.trim() || 'Not provided'}`,
    `Reviewer notes: ${document.getElementById('reviewer-notes').value.trim() || 'Not provided'}`
  ];
}

function updateScore() {
  hasCalculated = true;
  const score = buildScore();
  const output = document.getElementById('score-output');
  document.getElementById('total-score').textContent = `${score.total}`;
  document.getElementById('score-band').textContent = score.scoreBand;

  const fixList = document.getElementById('fix-list');
  fixList.innerHTML = '';
  score.recommendations.forEach((text) => {
    const li = document.createElement('li');
    li.textContent = text;
    fixList.appendChild(li);
  });
  document.getElementById('score-text').textContent = 'Here is your manual readiness scorecard summary.';
  output.classList.remove('hidden');

  const brandEmail = document.getElementById('brand-email').value.trim();
  const brandName = document.getElementById('brand-name').value.trim() || 'Your Brand';
  const ctaText = document.getElementById('cta-text').value.trim() || 'Preview scorecard email';
  const subject = `${brandName} - Manual readiness score ${score.total}/50`;
  const body = [
    'Manual Website Conversion-Readiness Scorecard summary',
    ...contextLines(),
    `Score: ${score.total}/50`,
    `Readiness band: ${score.scoreBand}`,
    'Criterion scores:',
    ...score.scored.map((item) => `- ${item.label}: ${item.value}/5`),
    'Top fixes:',
    ...score.recommendations.map((text) => `- ${text}`),
    'Generated by Manual Website Conversion-Readiness Scorecard preview. Manual scorecard only; not an automated audit or certification.'
  ].join('\n');

  const cta = document.getElementById('cta');
  if (usableEmail(brandEmail)) {
    cta.textContent = ctaText;
    cta.href = `mailto:${encodeURIComponent(brandEmail)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  } else {
    cta.textContent = 'Enter a real email to preview scorecard email';
    cta.removeAttribute('href');
  }
}

function syncSliderLabel(slider) {
  const label = slider.closest('fieldset').querySelector('legend').textContent;
  const span = slider.closest('label').querySelector('span').textContent;
  let output = slider.parentElement.querySelector('.slider-value');
  if (!output) {
    output = document.createElement('strong');
    output.className = 'slider-value';
    slider.parentElement.appendChild(output);
  }
  output.textContent = `${slider.value}/5`;
  slider.setAttribute('aria-label', `${label}: ${span} score ${slider.value} out of 5`);
}

function actionPlanText() {
  if (!hasCalculated) return 'No manual readiness score has been calculated yet.';
  const score = buildScore();
  return [
    'Manual Website Conversion-Readiness Scorecard summary',
    ...contextLines(),
    `Score: ${score.total}/50`,
    `Readiness band: ${score.scoreBand}`,
    'Criterion scores:',
    ...score.scored.map((item) => `- ${item.label}: ${item.value}/5`),
    'Top fixes:',
    ...score.recommendations.map((text) => `- ${text}`),
    'Manual scorecard only. Verify with professional SEO/accessibility/performance/security/legal review where needed.'
  ].join('\n');
}

async function copyActionPlan() {
  if (!hasCalculated) {
    document.getElementById('score-text').textContent = 'Calculate the manual readiness score before copying an action plan.';
    return;
  }
  const text = actionPlanText();
  try {
    await navigator.clipboard.writeText(text);
    document.getElementById('score-text').textContent = 'Action plan copied. Use it as a discovery aid, not as an automated certification.';
  } catch (error) {
    document.getElementById('score-text').textContent = text;
  }
}

function resetSampleScorecard() {
  hasCalculated = false;
  document.getElementById('score-output').classList.add('hidden');
  document.getElementById('score-text').textContent = 'Rate each criterion, then calculate the manual readiness score. No score has been assigned yet.';
  document.getElementById('brand-name').value = 'TWE Web Review';
  document.getElementById('brand-email').value = 'thewatchersedgestore@gmail.com';
  document.getElementById('cta-text').value = 'Order my website cleanup';
  document.getElementById('website-name').value = 'Sample Business Website';
  document.getElementById('website-url').value = 'https://example.ca';
  document.getElementById('reviewer-notes').value = 'Sample first-pass review notes; replace with the buyer-approved context.';
  document.querySelectorAll('#audit-form input[type=range]').forEach((slider) => {
    slider.value = 3;
    syncSliderLabel(slider);
  });
}

document.getElementById('score-btn').addEventListener('click', updateScore);
document.querySelectorAll('#audit-form input[type=range]').forEach((slider) => {
  syncSliderLabel(slider);
  slider.addEventListener('input', () => syncSliderLabel(slider));
});
document.getElementById('copy-summary').addEventListener('click', copyActionPlan);
document.getElementById('reset-sample').addEventListener('click', resetSampleScorecard);
document.getElementById('score-text').textContent = 'Rate each criterion, then calculate the manual readiness score. No score has been assigned yet.';
